jruby/activerecord-jdbc-adapter

lib/arjdbc/postgresql/base/pgconn.rb
lib/arjdbc/postgresql/oid_types.rb

Added minimal implementation of PGconn with unescape_bytea

---

lib/arjdbc/jdbc/type_cast.rb
test/db/postgresql/array_type_test.rb
test/db/postgresql/json_test.rb
test/db/postgresql/simple_test.rb
test/db/postgresql/types_test.rb

Reverted tests mistakenly adjusted to AR42
Tests are green for PostgreSQL locally for AR41 and AR42.

Allow reading "infinity" and "BC timestamps

---

lib/arjdbc/postgresql/adapter.rb
lib/arjdbc/postgresql/oid/bytea.rb
lib/arjdbc/postgresql/oid_types.rb

Use the "E" prefix to mark the input as escaped binary data, and do not unescape when reading the data back from the DB.
Fixes #675

Store binary data as-is for PostgreSQL

---

lib/arel/visitors/h2.rb
lib/arel/visitors/hsqldb.rb
test/db/hsqldb/offset_test.rb

Adds a test for LIMIT and OFFSET including having an OFFSET without a LIMIT.  This was broken for older versions of AR as well, but fixed now.

Fix H2/HSQLDB LIMIT and OFFSET with AR 4.2

---

lib/arjdbc/mysql/adapter.rb

Same PR as https://github.com/jruby/activerecord-jdbc-adapter/pull/694 but aiming to target the next 1.3 release.

Fixed MySQL primary key for MySQL >= 5.7.3

---

lib/arjdbc/h2/adapter.rb

It appears that when I create a model class, and invoke `create!` using h2, the ID (primary key) field on the returned object is always `0`. After some investigation, it appears that the code exists in the h2 adapter to address this, but the `Column` module wasn't getting used. I've copied the pattern used in the Oracle adapter to use that module. 
My environment:
ARJDBC: 1.3.20
JRuby: 1.7.20
Rails: 4.1.1
h2 driver: 1.4.187
Java: 1.8.0_66
In my application, where the problem was encountered, the h2 connection is setup externally, in some custom Java code.

Ensuring that H2 uses custom column class.

---

src/java/arjdbc/mysql/MySQLRubyJdbcConnection.java

When retrieving data for a BINARY column with the MySQL adapter, the adapter is allocating 2K for each field and is being read as a stream. However I believe MySQL only allows a size of 255 bytes for BINARY and VARBINARY fields. For example this causes excessive memory to be consumed when retrieving a large number(100K+) of binary ids (UUIDs).
This is a fix for: https://github.com/jruby/activerecord-jdbc-adapter/issues/741
BINARY treated as stream:
https://github.com/jruby/activerecord-jdbc-adapter/blob/e9366a5a25dc919e7fe7d6319410aec2e9532edb/src/java/arjdbc/jdbc/RubyJdbcConnection.java#L2161
https://github.com/jruby/activerecord-jdbc-adapter/blob/e9366a5a25dc919e7fe7d6319410aec2e9532edb/src/java/arjdbc/jdbc/RubyJdbcConnection.java#L2464-L2481
Storage requirements for MySQL BINARY and …

Reduce memory consumption when retrieving BINARY columns with MySQL adapter

---

lib/arjdbc/mssql/adapter.rb
test/db/mssql/ignore_system_views_test.rb
test/db/mssql/simple_test.rb

Changed selects from information schema to uppercase.
If MS SQL database has case sensitive collation, then information schema views must be accessed with uppercase schema and view names.

Mssql with case sensitive collation

---

Gemfile

This PR makes bundle install not output a warning.

Gemfile: kares/yard-method-overrides over HTTPS

---

jdbc-h2/jdbc-h2.gemspec

Point gem homepage to jdbc-h2 instead of jdbc-hsqldb

Update Gem Homepage

---

rakelib/db.rake

This pull request addresses this error when `rails-5` branch tested with MySQL 5.7.
- Steps to reproduce
``` ruby
$ git checkout rails-5
$ bundle exec rake test_mysql
Creating MySQL (test) database: arjdbc_test
ERROR 1133 (42000) at line 3: Can't find any matching row in the user table
rake aborted!
Command failed with status (1): [cat /tmp/mysql20160519-4782-1dsvwfl | /usr...]
/home/yahonda/git/activerecord-jdbc-adapter/rakelib/db.rake:23:in `block in (root)'
/home/yahonda/.rbenv/versions/jruby-9.1.0.0/bin/bundle:22:in `<top>'
Tasks: TOP => test_mysql => db:mysql
(See full trace by running task with --trace)
```
Since MySQL 5.7 `grant` statements will not create database users anymore. https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-7.html
> In MySQL 5.7.6, the …

Execute CREATE USER explicitly to support MySQL 5.7

---

lib/arjdbc/mssql/adapter.rb

This error message is very unlikely to happen, but it did, when JRuby had a bug with Regexes: jruby/jruby/#3670
Knowing, that the generated query was OK would have saved us many hours thinking about our queries...

Improve message for 'no columns for table' error

---

lib/arjdbc/jdbc/type_converter.rb

We are using a legacy Sybase DB and we have the long varchar type in use.
The "text" data type presented on line 35 is an alias for that type in Sybase, but for legacy codebases
the long varchar will probably be in use as it happens for us.

Added long varchar to type converter for legacy sybase DB

---

lib/arjdbc/mysql/adapter.rb

I tried the MySQL adaptor on rails 5 and I got the following error.
```
NoMethodError: undefined method `name' for #<Hash:0x6da646b8>
block in columns_hash at /Users/sgnr/.gem/jruby/2.3.1/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/schema_cache.rb:63
```
The cause of this seems to be `ArJdbc::MySQL#column` that call `map!`, but `map!` has [a surprising behaviour on `ActiveRecord::Result`](https://github.com/rails/rails/blob/6cd65861e93250159b19eac5b990a100f566e0ff/activerecord/lib/active_record/result.rb#L60): it just ends up invoking `map`. I guess that code never returned an array of column, but the caller was fine with an array of hashes?

Avoid map! on result object.

---

lib/arjdbc/jdbc.rb

This solve the error in rails 5.1:
Bundler::GemRequireError: There was an error while trying to load the gem 'activerecord-jdbcpostgresql-adapter'.
Gem Load Error is: uninitialized constant ActiveRecord::ConnectionAdapters::PostgreSQL::ColumnDefinition

Error PostgreSQL::ColumnDefinition

---

test/db/db2/rake_test.rb

Overridden `db_config` was discarding the URL. In the case of as400, this url was needed to prevent it from poping up a dialog and asking to provide additional data

[as400] Fixed issue when a GUI dialog popus and asks to log in

---

lib/arjdbc/tasks/database_tasks.rb

AS400 was missing the `DB2DatabaseTasks` module

[as400] Database tasks fix

---

lib/arjdbc/db2/as400.rb

Added truncate functionality
This can also be achieved by calling the `CLRPFM` command but going though SQL is much less hassle. This will not restart the auto-incremented fields

[as400] Added truncate

---

lib/arjdbc/db2/as400.rb

AS400 throws an exception if you try to run `ADDRPYLE SEQNBR(9876) MSGID(CPA32B2) RPY('I')` more than once per login. This was causing some issues in the testing environment

[as400] Don't throw an exception if sequence number was defined

---

test/db/postgresql/json_test.rb
test/db/postgresql/jsonb_test.rb
test/db/postgresql/oid_types_test.rb

Updated the style to be more like the old_type_test.rb file. I removed the `test_type_cast_json` and `test_type_cast_jsonb` tests since they are essentially testing built in ActiveRecord functionality at this point.

Fix json type tests

---

lib/arjdbc/postgresql/adapter.rb
test/db/postgresql/schema_dump_test.rb

I was able to mostly reuse the built in functionality from ActiveRecord's Postgres adapter. There were a couple of small output changes in ActiveRecord for indexes and bigints that required tests to be updated.

Fix postgres schema dumping for Rails 5.0

---

lib/arjdbc/postgresql/connection_methods.rb
lib/arjdbc/tasks/db2_database_tasks.rb
test/db/postgresql/ltree_test.rb
test/db/postgresql/rake_test.rb
test/db/postgresql/schema_test.rb
test/db/postgresql/types_test.rb

Most of the changes in this PR are cleaning up warnings and removing conditional tests.
Some tests that were fixed:
- ltree tests were updated so they will run if possible instead of always being omitted
- An ActiveRecord::NoDatabaseError is now thrown when attempting to connect to a DB that doesn't exist, this fixes one of the rake tests and matches core ActiveRecord functionality
- the schema_search_path test was updated because now there are spaces between schemas in the path

Misc postgres test fixes

---

lib/arjdbc/postgresql/adapter.rb
lib/arjdbc/postgresql/base/pgconn.rb
src/java/arjdbc/jdbc/RubyJdbcConnection.java

In ActiveRecord 5.0.3 or 5.0.4 they updated `PGConn` references to be `PG::Connection` since `PGConn` was deprecated.
Should I also include the compiled jar file for the adapter with the pr or should that not be in the repo?

Postgres rails 5.0.4 fixes

---

lib/arjdbc/postgresql/adapter.rb
test/db/postgresql/connection_test.rb

ActiveRecord 5.0 deprecated `insert_sql`, `update_sql`, and `delete_sql`. Only `insert_sql` appears to be implemented at this point.

Deprecate PostgreSQLAdapter#insert_sql

---

lib/arjdbc/jdbc/adapter.rb
lib/arjdbc/postgresql/adapter.rb

Removed some logic that was overwriting ActiveRecord's built in primary key handling and breaking some tests. The logic that was being overwritten was:
```
def primary_key(table_name)
pk = primary_keys(table_name)
pk = pk.first unless pk.size > 1
pk
end
```
This change makes it so that composite keys will be returned instead of being hidden and ActiveRecord will emit a warning about composite keys not being supported. This fixes the tests in the ActiveRecord test suite that specifically test that the warning is emitted.

Fix some ActiveRecord primary key tests for postgres adapter

---

lib/arjdbc/postgresql/base/array_decoder.rb
lib/arjdbc/postgresql/base/array_encoder.rb
lib/arjdbc/postgresql/base/pgconn.rb

This makes it so that the PG modules/classes that we are emulating will be scoped to where they are referenced so that it doesn't look like the pg gem is loaded for others that may be checking `defined? PG`. This addresses concerns raised in: https://github.com/jruby/activerecord-jdbc-adapter/pull/804#discussion_r128342423

Scope PG namespace

---

lib/arjdbc/jdbc/adapter.rb
lib/arjdbc/postgresql/adapter.rb

Updated the adapter to use more of ActiveRecord's logic. Most of the changes in here are just deleting methods that are now coming from `ActiveRecord::ConnectionAdapters::PostgreSQL::DatabaseStatements`

Postgres adapter cleanup

---

lib/arjdbc/postgresql/adapter.rb
lib/arjdbc/postgresql/column.rb

There were a few schema dumping tests that were failing due to indexes not being read out of the DB correctly and a couple that expected more specific type support.
The changes to the `indexes` method are mostly taken from AR's postgres adapter.

Fixed schema dumping for postgres adapter in Rails 5

---

src/java/arjdbc/jdbc/RubyJdbcConnection.java

This just cherry picks some commits from the master branch so that the tests will be passing on the rails-5 branch.

Fix transaction isolation tests for Rails 5

---

test/rake_test_support.rb

since `ActiveRecord::Migrator.schema_migrations_table_name`
will be deprecated in 5.2.
Refer https://github.com/rails/rails/pull/28293
This pull request suppresses the following deprecation warning.
```ruby
$ rake test_postgresql
... snip ...
Dropped database 'test_rake_db'
.DEPRECATION WARNING: schema_migrations_table_name is deprecated and will be removed from Rails 5.2 (called from create_schema_migrations_table at /home/ubuntu/activerecord-jdbc-adapter/test/rake_test_support.rb:122)
```

Use `ActiveRecord::SchemaMigration.table_name`

---

test/db/mysql/rake_test.rb

This pull request suppresses these two warnings.
```ruby
$ rake test_mysql
... snip ...
Using ActiveRecord::VERSION = 5.1.4
/home/ubuntu/activerecord-jdbc-adapter/test/db/mysql/rake_test.rb:89: warning: Ambiguous first argument; make sure.
/home/ubuntu/activerecord-jdbc-adapter/test/db/mysql/rake_test.rb:115: warning: Ambiguous first argument; make sure.
```

Address ` warning: Ambiguous first argument; make sure.`

---

.travis.yml
Gemfile
rakelib/02-test.rake
rakelib/db.rake
rakelib/rails.rake
test/db/postgresql/schema_test.rb
test/rails/config.yml
test/rails/excludes/mysql2/Mysql2ConnectionTest.rb

previous tasks are left in ... `rake rails:test:sqlite3` still works
... new syntax is `rake rails:test_sqlite3` - uses AR-JDBC's dependencies, also faster to boot up.

get rails tests to run (on CI)

---

lib/arjdbc/postgresql/adapter.rb

Refer https://github.com/rails/rails/pull/26784
This pull request addresses these 3 errors:
```ruby
$ bundle install
$ ARCONN=jdbcpostgresql bin/test test/cases/view_test.rb
Using jdbcpostgresql
Run options: --seed 28409
.E.E.E..............
Finished in 2.083744s, 9.5981 runs/s, 9.1182 assertions/s.
1) Error:
ViewWithPrimaryKeyTest#test_column_definitions:
ActiveRecord::StatementInvalid: ActiveRecord::JDBCError: org.postgresql.util.PSQLException: ERROR: unterminated quoted identifier at or near ""'::regclass
AND a.attnum > 0 AND NOT a.attisdropped
ORDER BY a.attnum
"
Position: 556:         SELECT a.attname, format_type(a.atttypid, a.atttypmod),
pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
(SELECT c.collname FROM …
```

Support view names with single quote

---

lib/arjdbc/sqlite3/adapter.rb

Refer https://github.com/rails/rails/pull/27701
This pull request addresses these two failures:
```
$ bundle install
$ ARCONN=jdbcsqlite3 bin/test test/cases/adapter_test.rb -n /test_foreign_key_violations/
```
```ruby
$ ARCONN=jdbcsqlite3 bin/test test/cases/adapter_test.rb -n /test_foreign_key_violations/
Using jdbcsqlite3
Run options: -n /test_foreign_key_violations/ --seed 41207
FF
Finished in 0.080637s, 24.8025 runs/s, 24.8025 assertions/s.
1) Failure:
ActiveRecord::AdapterForeignKeyTest#test_foreign_key_violations_are_translated_to_specific_exception [/home/yahonda/git/rails/activerecord/test/cases/adapter_test.rb:288]:
ActiveRecord::InvalidForeignKey expected but nothing was raised.
2) Failure: …
```

Execute `configure_connection` to enable foreign keys at sqlite3 adapter

---

lib/arjdbc/sqlite3/adapter.rb

Refer https://github.com/rails/rails/commit/c92757fb68f
This pull request addresses the following failure.
```ruby
$ bundle
$ bin/test test/cases/migration/columns_test.rb:234
Using jdbcsqlite3
Run options: --seed 4959
F
Finished in 0.281328s, 3.5546 runs/s, 7.1091 assertions/s.
1) Failure:
ActiveRecord::Migration::ColumnsTest#test_change_column_to_drop_default_with_null_false [/home/yahonda/git/rails/activerecord/test/cases/migration/columns_test.rb:234]:
Expected true to be nil or false
1 runs, 2 assertions, 1 failures, 0 errors, 0 skips
$
```

Fix `change_column` to drop default with `null: false`

---

test/db/mysql/simple_test.rb

This pull request addresses the folloiwng warning.
```ruby
$ rake test_mysql
Using ActiveRecord::VERSION = 5.1.4
/home/yahonda/git/activerecord-jdbc-adapter/test/db/mysql/simple_test.rb:191:
warning: Ambiguous first argument; make sure.
```

Address `warning: Ambiguous first argument; make sure.`

---

lib/arjdbc/abstract/transaction_support.rb
lib/arjdbc/mysql/adapter.rb
lib/arjdbc/postgresql/adapter.rb
lib/arjdbc/sqlite3/adapter.rb
test/transaction_test_methods.rb

Let `supports_transaction_isolation?` have the same method signature with Active Record
This pull request the following failure.
```ruby
$ bundle install
$ ARCONN=jdbcmysql bin/test test/cases/transaction_isolation_test.rb:11
Using jdbcmysql
Run options: --seed 8415
F
Finished in 0.069170s, 14.4571 runs/s, 14.4571 assertions/s.
1) Failure:
TransactionIsolationUnsupportedTest#test_setting_the_isolation_level_raises_an_error
[/home/yahonda/git/rails/activerecord/test/cases/transaction_isolation_test.rb:11]:
ActiveRecord::TransactionIsolationError expected but nothing was raised.
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
$
```
It also removes `test_supports_transaction_isolation` test expecting
`supports_transaction_isolation?` …

Let `supports_transaction_isolation?` have the same method signature

---

Gemfile

Delete minitest-excludes from Gemfile to address `warning: loading in progress, circular require considered harmful`
Even with [minitest excluded for now since it is broken on travis
](https://github.com/jruby/activerecord-jdbc-adapter/commit/eccdf007ff118734d4888d0197eb86f6f60d9bc5 ) it is getting this warning below https://travis-ci.org/jruby/activerecord-jdbc-adapter/jobs/309757276 
```ruby
/home/travis/.rvm/gems/jruby-9.1.14.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292: warning: loading in progress, circular require considered harmful - /home/travis/.rvm/gems/jruby-9.1.14.0/gems/minitest-5.3.3/lib/minitest/test.rb
```
Refer #852

Delete minitest-excludes from Gemfile

---

Gemfile
rakelib/rails.rake

This pull request addresses #852 and restore `minitest-excludes` feature. 
Somehow in my environment, it needs to remove ` require: nil` for `mintest`

 Restore `minitest-excludes` feature

---

lib/arjdbc/mysql/adapter.rb

from `create_table` method
Closes #833
These options are unnecessary as Rails `AbstractMysqlAdapter` does not specify them.
https://github.com/rails/rails/blob/5-1-stable/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb#L362-L364
```ruby
def create_table(table_name, **options) #:nodoc:
super(table_name, options: "ENGINE=InnoDB", **options)
end
```

Remove unnecessary `CHARSET=utf8 COLLATE=utf8_general_ci`

---

.travis.yml
test/rails/config.yml

... seems that by doing so there's much more failures with Postgres' (rails tests) than currently
but I believe this is the test setup we should be going towards - explicitly not having a setup such as : 
```
production:
insert_returning: ""
prepared_statements: ""
```
maybe there's just one issue underneath the failures (check the rails:test_postgresql target on CI - the one without any ENV vars) otherwise it would mean the adapter is still not much in shape

[test] tune/more rails tests - leave PG config to its defaults

---

src/java/arjdbc/postgresql/ByteaUtils.java

This is to avoid arrayIndexOutOfBoundsException in the main unescape loop.  It only happens when unescaping non-escaped content.

Increment index when counting octal escapes

---

lib/arjdbc/oracle/adapter.rb

Oracle application users are currently broken in 1.3.x, the SELECT that tries to determine the proper sequences and primary key uses a nil owner and fails. This is a quick fix that will set the schema_owner to the schema name if set.

fix schema config for Oracle application users

---

lib/arjdbc/postgresql/adapter.rb

The pull request is an attempt to remove the duplicate method definition `max_identifier_length`

Remove duplicate method definition

---

src/java/arjdbc/postgresql/PostgreSQLRubyJdbcConnection.java
test/db/postgresql/types_test.rb

When using BigDecimal for money values, the standard handling with
setPGobjectParameter() does not work since it does a toString() on the
value. For a BigDecimal("123.45") this will produce "0.12345e3" which
PG doesn't like.
This registers a handler for PG type "money" which uses
statement.setBigDecimal() when a RubyBigDecimal is provided and falls
back to the standard handling setPGobjectParameter() for everything
else.
This fixes test errors:
* ajrdbc: test/db/postgresql/types_test.rb#test_update_money
* rails: test/cases/adapters/postgresql/money_test.rb#test_create_and_update_money

[50-stable, postgres]: Improve handling of DB type "money"

---

lib/arjdbc/mysql/adapter.rb

Rails 5.2 introduced a insert_fixtures_set() with special optimization
for MySQL, namely using multiple statements in one call. This requires
the connection params to be set up and a method with_multi_statements
that we're not (yet) implementing. The C version changes flags of the
connection for that.
The easy fix is to just use the plain loop from the SQLite3 adapter.
This is slower than it could be, but at least the Rails tests run again
with this. And it looks pretty nice already:
5459 runs, 15416 assertions, 15 failures, 6 errors, 5 skips
(that's with jruby-9.2 so two of the failures are about FrozenError..)

[52, mysql] make fixtures work and Rails test run agin

---

test/rails/excludes/sqlite3/ActiveRecord/DatabaseTasksMigrateTest.rb
test/rails/excludes/sqlite3/ActiveRecord/Migration/PendingMigrationsTest.rb

5 test errors less on the AR 5.2 test...

[52, sqlite] Exclude some AR 5.2 that rely on sqlite3-ruby API

---

test/db/mysql/simple_test.rb

In AR 5.2, INDEX_TYPES got removed, so just drop the test

[52, mysql] Remove test_mysql_indexes

---

lib/arjdbc/postgresql/adapter.rb
test/explain_support_test_methods.rb
test/test_helper.rb

In Arel 9 used in AR 5.2, the way bind params work has changed:
https://github.com/rails/arel/commit/db1bb4e9a728a437d16f8bdb48c3b772c3e4edb0
The values are now stored directly in the BindParam itself.
With this change, to_sql() in AR 5.2 now either accepts an Arel AST w/o
any binds or a SQL string with binds.
Change the tests to use the new syntax and test both ways. With this
in place fix PG explain with an Arel AST. Using to_sql() leads to no
binds at all and in turn makes PG complain. Instead use to_sql_and_bind()
which extracts the actual bind values from the Arel AST.
(Pretty sure plain AR5.2 on MRI is broken here for PG)

[test, postgres, sqlite] Fix explain with binds

---

test/explain_support_test_methods.rb

This version of explain is for Arel < 9 and cannot work w/o prepared
statements. The new-style Arel with bind values included in the AST
works fine. So just skip the test.

Skip test_explain_with_binds when PREPARED_STATEMENTS=false

---

lib/arjdbc/mysql/adapter.rb
test/rails/excludes/mysql2/FixturesTest.rb

This is a follow-up for a8a2d41
([mysql] make fixtures work and Rails 5.2 test run again (#909))
* Adds the missing #default_insert_value(). This fixes a problem
with auto_increment primary keys.
* Implements dummy methods to make the standard insert_fixtures_set()
code work properly.
* Exclude some tests that are bulk insert specific
This makes all of these pass:
* rails52/test/cases/fixtures_test.rb
Proper bulk insert can be implemented later, ideally using JDBC
addBatch()/executeBatch() instead of manually concatenating statements.

[52, mysql] Fix rails fixtures tests

---

lib/arjdbc/sqlite3/adapter.rb

See diff. Calling super from this method leads to an infinite loop
of the method calling itself and pretty soon to a stack overflow.
This only happens in 9.1, things work ok in 9.2
To reproduce this is:
> rake rails:test_sqlite3 TEST=test/cases/migration_test.rb
The method #translate_exception is implemented in
* class ActiveRecord::ConnectionAdapters::AbstractAdapter
* module ArJdbc::Core
* module ArJdbc::SQLite3
The Arjdbc class SQLiteAdapter < AbstractAdapter includes both
modules. Yet calling super from the method in SQLite3 causes an infinite
loop in 9.1. Moving it from the module to the class solves the problem.
Interestingly, the Postgres adapter does the same w/o problems.
The relevant stack traces (cleaned up a bit for readability). Run with
JRuby 9.1.17.0, Java HotSpot(TM) …

WIP/RFC: [52, sqlite3] Work around JRuby 9.1.x bug calling "super"

---

test/rails/excludes/mysql2/ActiveRecord/MysqlDBCreateWithInvalidPermissionsTest.rb
test/rails/excludes/mysql2/AttributeMethodsTest.rb
test/rails/excludes/mysql2/Mysql2ConnectionTest.rb

* Exclude tests relying on mysql2 gem internals
* Rename an exclude where rails fixed a typo
* Delete an exclude for a test that no longer exists

[52, mysql] Update some rails test excludes

---

src/java/arjdbc/jdbc/RubyJdbcConnection.java

PG JDBC driver doesn't like "character varying" when constructing arrays.
Using "text" as type works for insert/update, but results in a
ERROR: operator does not exist: character varying[] = text[]
when used in a WHERE clause. "varchar" is the right type for the
JDBC driver
Fixes errors in:
* rails52/test/cases/adapters/postgresql/array_test.rb #test_uniqueness_validation
* rails52/test/cases/adapters/postgresql/array_test.rb #test_where_by_attribute_with_array

[postgres] Fix varchar arrays in WHERE clause

---

lib/arjdbc/abstract/database_statements.rb
lib/arjdbc/abstract/statement_cache.rb

It's deprecated in Rails 5.2 and always returns true. For now, just
deprecate in ARJDBC to be able to disable the cache.
Fixes:
* rails52/test/cases/bind_parameter_test.rb #test_deprecate_supports_statement_cache

[52] Deprecate supports_statement_cache?

---

.travis.yml

By default Travis uses PG 9.2. But it seems the client is actually newer
than that. One of the test errors is the server complaining about
"lock_timeout" which is a 9.3+ thing. Using a newer server version
fixes the problem. 9.2 is EOL anyway and 9.3 will be in a few weeks,
so go for 9.4

Travis: use postgresql-9.4

---

rakelib/db.rake

MariaDB 10.1+ insists on CREATE USER. Since "IF EXISTS" for CREATE/DROP
is only supported in more recent versions, just silently drop the user
before.
While at it, make the whole file a bit more readable.

[50-52, MariaDB] fix "rake db:mysql" for MariaDB >= 10.1

---

lib/arjdbc/postgresql/adapter.rb
test/rails/excludes/postgresql/ActiveRecord/ConnectionAdapters/PostgreSQLAdapterTest.rb

It's all about quoting. The AR implementation undoes the proper
quoting. serial_sequence() returns a properly quoted string, the fallback
should actually never be used in PG >= 8.0

[50-52, postgres] Fix insert_returning: false for mixed case tables

---

lib/arjdbc/postgresql/adapter.rb

Only JDBC errors are handled by the adapter specific version of
translate_exception(), everything else should be handled by the
super implementation. It accidentally turned an ActiveModel::RangeError
into an ActiveRecord::RangeError, failing finder tests.
Fixes two errors (Rails 5.1 and 5.2) in
* rails/test/cases/finder_test.rb

[51-52, postgres] Fix translate_exception()

---

lib/arjdbc/postgresql/adapter.rb

Fixes:
* rails52/test/cases/migration/foreign_key_test.rb

[52, postgres] supports_validate_constraints?

---

lib/arjdbc/postgresql/oid_types.rb

OID::Date is new for PostgreSQL adapter in Rails 5.2
Fixes 2 failures in:
* rails52/test/cases/adapters/postgresql/infinity_test.rb

[52, postgres] Register type "date" as OID::Date

---

lib/arjdbc/postgresql/adapter.rb
lib/arjdbc/postgresql/connection_methods.rb

The pgjdbc driver internally caches parsed statements (the most heavy
part of prepareStatement()). The hot_compatibility.rb test for INSERT
fails because the internal cache is used, not the ARJDBC one (only used
for queries).
Setting the option "autosave = ' conservative'", the driver handles
the cached plan changes internally: it creates a savepoint before the
query, when the problem is hit, it rolls back to the savepoint, clears
the cache and retries. This works for all statements and even when
inside a transaction. No more special handling required.
Fixes:
* rails/test/cases/hot_compatibility_test.rb

[postgres] Use pgjdbc "autosave" option for hot compat

---

src/java/arjdbc/jdbc/RubyJdbcConnection.java

When inside a transaction, never retry any statements. Retrying
transient errors is wrong as the transaction is typically already
rolled back. Retrying then only re-does the last statement, possibly
in a series of multiple statements, leading to unnoticed data loss.
The MySQL driver for example throws a MySQLTransactionRollbackException
when a deadlock is found. This inherits from MySQLTransientException
which inherits from SQLTransientException. The transaction is already
rolled back when the last statement was retried.
Fixes:
* rails/test/cases/adapters/mysql2/transaction_test.rb

[50-52, core] Fix exception handling within transaction

---

rakelib/compile.rake

Both Rakefile and `compile.rake` define the task
`lib/arjdbc/jdbc/adapter_java.jar`. So, while calling `rake` to compile
the gem, the task gets invoked twice - First from Rakefile followed by
the task defined in `compile.rake`. The classpath issue for Java 9+ was
fixed in Rakefile but not in `rakelib/compile.rake`.

Add location of jruby.jar to classpath from rbconfig for java 9+

---

lib/arjdbc/postgresql/adapter.rb

This mostly makes sure that the tests for these features are
actually executed.

[50-52, postgres] Add missing supports_x? methods

---

lib/arjdbc/postgresql/adapter.rb
test/db/postgresql/version_test.rb

Do the same as libpq, see
https://github.com/postgres/postgres/blob/master/src/interfaces/libpq/fe-exec.c

[50-52, postgres] Fix PG version parsing for PG >= 10

---

lib/arjdbc/db2/adapter.rb
lib/arjdbc/db2/as400.rb
lib/arjdbc/db2/column.rb
lib/arjdbc/db2/connection_methods.rb
lib/arjdbc/jdbc.rb
lib/arjdbc/jdbc/column.rb

Fixes https://github.com/jruby/activerecord-jdbc-adapter/issues/955 and adds basic support for DB2/AS400
Had to add ArJcbc::AR52 to the JdbcColumn class to initialize adapter.

[db2] Add DB2 and AS400 support  for AR52

---

lib/arjdbc/abstract/core.rb
lib/arjdbc/jdbc/adapter.rb

- Log in rails dev server console now shows where query was executed from
- `User.exists? 1` won't fail due to ID not being passed

Fixed for AR52

---

lib/arjdbc/db2/adapter.rb

Currently migrations are failing on AR5.2 because the `type_to_sql` was changed from 4 parameters to 2 parameters. 
Changed the method in db2 adapter to match this

Changed params of type_to_sql to match the ones of AR5.2

---

.travis.yml

Recent release of Bundler 2.0 breaks the build since it cannot install
with older rubygems version. Make sure 1.17.3 is installed.

[ci] Make sure Travis uses Bundler 1.17.3 but not 2.x

---

lib/arjdbc/db2/adapter.rb

When inserting into view's or tables with no ID, exception will be thrown even though the insert goes fine
Code will return `nil` if the result is blank

[AR52] Ability to handle nil last_inserted_id result

---

lib/arjdbc/postgresql/adapter.rb
test/bind_params_length_test.rb
test/db/mysql/bind_params_length_test.rb
test/db/postgresql/bind_params_length_test.rb

pgjdbc doesn't like more than 32767 bind params.
Fixes #977

[postgres] fix bind params length

---

.travis.yml
lib/arjdbc/abstract/core.rb
pom.xml
test/rails/excludes/mysql2/LogSubscriberTest.rb
test/rails/excludes/postgresql/LogSubscriberTest.rb
test/rails/excludes/sqlite3/LogSubscriberTest.rb

Once JRuby 9.2.6.0 is released and the .travis.yml is changed to use it, this _should_ turn CI green for Rails 6.0.0.beta1.

Random Rails 6 bits

---

test/simple.rb
test/test_helper.rb

5.1 and higher changed the way cached queries are accounted for...
Fixes #839

[test] fix query cache tests for Rail 5.1..6.0

---

test/simple.rb

This is already in 52-stable. With latest Rails 5.0.x, it happens too.

[test] fix some ArgumentError: argument out of range

---

.travis.yml
lib/arjdbc/postgresql/adapter.rb
test/rails/excludes/mysql2/AttributeMethodsTest.rb
test/rails/excludes/mysql2/Mysql2ConnectionTest.rb
test/test_helper.rb

One fallout from the 50-stable merge, CI Rails version update, excludes update and one for SQLite3 that probably doesn't trigger for 51-stable, but it sure does for 52-stable.
The remaining two errors on PG I have no idea about yet...test and rake tasks are the same as in Rails 5.2.
This will likely result in conflicts in the 52-merge. Anyways, once this is in, another PR for 52-stable will follow soon after.

51.x fixes

---

lib/arjdbc/sqlite3/adapter.rb

Since Rails now needs it public. Since https://github.com/rails/rails/pull/35795.

Make `check_version` public

---

activerecord-jdbcderby-adapter/activerecord-jdbcderby-adapter.gemspec

The RubyGems gemspec property `rubyforge_project` has been removed without a replacement. This PR removes that property.
* [RubyForge was closed down in 2013][1].
* [rubygems/rubygems#2436 deprecated the `rubyforge_project` property][2].
[1]: https://twitter.com/evanphx/status/399552820380053505
[2]: rubygems/rubygems#2436

gemspec: Drop rubyforge_project property

---

activerecord-jdbch2-adapter/activerecord-jdbch2-adapter.gemspec
activerecord-jdbchsqldb-adapter/activerecord-jdbchsqldb-adapter.gemspec
activerecord-jdbcmssql-adapter/activerecord-jdbcmssql-adapter.gemspec
activerecord-jdbcmysql-adapter/activerecord-jdbcmysql-adapter.gemspec
activerecord-jdbcpostgresql-adapter/activerecord-jdbcpostgresql-adapter.gemspec
activerecord-jdbcsqlite3-adapter/activerecord-jdbcsqlite3-adapter.gemspec

The RubyGems gemspec property `rubyforge_project` has been removed without a replacement. This PR removes that property.
* [RubyForge was closed down in 2013][1].
* [rubygems/rubygems#2436 deprecated the `rubyforge_project` property][2].
[1]: https://twitter.com/evanphx/status/399552820380053505
[2]: rubygems/rubygems#2436

Drop gemspec property rubyforge_project

---

src/java/arjdbc/mysql/MySQLRubyJdbcConnection.java

mysql-connector-java 8 is the recommended connector for all mysql versions, including mysql 5.5, 5.6, and 5.7: https://dev.mysql.com/downloads/connector/j/
This PR fixes this NPE when using mysql-connector-java version 8:
```
LoadError: load error: /Users/clark.perkins/Workspace/activerecord-jdbc-adapter/test/db/mysql/schema_dump_test -- java.lang.NullPointerException: null
require at org/jruby/RubyKernel.java:956
block in require at /Users/clark.perkins/.rvm/gems/jruby-9.1.17.0@jdbc/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274
load_dependency at /Users/clark.perkins/.rvm/gems/jruby-9.1.17.0@jdbc/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240
require at /Users/clark.perkins/.rvm/gems/jruby-9.1.17.0@jdbc/gems/activesupport-4.2.11.1/lib/active_suppor …
```

 Fixing cancel timer logic to work with mysql-connector-java 8

---

lib/arjdbc/abstract/database_statements.rb

Works with AR, breaks with AR-JDBC. Fix it by pushing the conversion down
to the actual methods, remove the higher-level wrappers.
Fixes #1033

[core] fix legacy binds when directly using exec_* methods

---

lib/arjdbc/abstract/database_statements.rb
lib/arjdbc/postgresql/column.rb

Here we have
* better support PG v10 and higher for 5x regarding schema dump and default values. This is already in master but with a minor syntax detail changed for JRuby 9.1 support.
* Legacy binds. This is already in 52-stable. Not that important.

postgreSQL fixes from master

---

lib/arjdbc/db2/column.rb
lib/arjdbc/derby/adapter.rb
lib/arjdbc/firebird/adapter.rb
lib/arjdbc/h2/adapter.rb
lib/arjdbc/hsqldb/adapter.rb
lib/arjdbc/informix/adapter.rb
lib/arjdbc/sqlite3/adapter.rb

Method hasn't been part of ActiveRecord since commit
https://github.com/rails/rails/commit/0b682e4b05c8f58c77c655650af6638c483ac903
(May 2014)

Remove unused simplified_type method

---

src/java/arjdbc/util/DateTimeUtils.java

With Rails 6.1, there's no conversion to a Time anymore for a DateTime
if it's already UTC. So what happens is that we call #to_time where
we dind't before. Since Rails overrides that for DateTime to basically
do #getlocal, the result is off.
Using RubyDateTime directly avoids the problem and is faster anyway.

[core] use RubyDateTime directly to create a string

---

.gitignore
lib/arjdbc/abstract/database_statements.rb
lib/arjdbc/mysql/connection_methods.rb
lib/arjdbc/postgresql/connection_methods.rb
lib/arjdbc/sqlite3/connection_methods.rb
rakelib/rails.rake
src/java/arjdbc/jdbc/RubyJdbcConnection.java
test/db/mysql/unit_test.rb
test/db/postgresql/primary_key_is_not_the_first_column_test.rb
test/db/postgresql/unit_test.rb

This is mainly some "fallout" from ongoing work for Rails 6.1 (i.e. master) support

Various fixes

---

lib/arjdbc/postgresql/adapter.rb
lib/arjdbc/sqlite3/adapter.rb

This fixes things with 6-0-stable branch again. The first and last commit is actually stuff that is already on master. Problem is that this alone would break the current stable Rails 6.0.2 because of an internal API change that got back-ported from 6.1. The commit in the middle fixes this.
This will cause a merge-conflict during 60-stable -> master merge. Resolution is simple: master shouldn't change 😉

Rails 6.0 fixes

---

.travis.yml
src/java/arjdbc/postgresql/PostgreSQLRubyJdbcConnection.java
test/db/postgresql/date_test.rb

e.g. when running with JRUBY_OPTS=-J-Duser.timezone=America/Detroit
any date saves is a day behind. Also tested with Asia/Anadyr.

[postgres] fix setting date when timezone offset is negative

---

src/java/arjdbc/mssql/MSSQLRubyJdbcConnection.java

Noticed the test suite started failing for the activerecord-jdbcsqlserver-adapter gem after the latest version and tracked it down to MSSQL's driver not playing nice. I believe this change will need to be applied to all the branches. After we release the changes, I'll release a new version of the jdbcsqlserver gem that bumps the required version for this gem.

Fix mssql failure when inserting into tables with composite primary keys

---

lib/arjdbc/jdbc/adapter.rb
lib/arjdbc/util/table_copier.rb

Hi,
git.io URL has been deprecated, and it will stop redirecting on April 29, 2022.
For more detail:
https://github.blog/changelog/2022-04-25-git-io-deprecation/

Replace git.io URL

---

lib/arjdbc/abstract/database_statements.rb
lib/arjdbc/sqlite3/adapter.rb

This adds support for the query tagging feature and updates the sqlite adapter to match how the typemap is created in ActiveRecord.

Fix some activerecord spec failures for Rails 7 support

---

src/java/arjdbc/jdbc/RubyJdbcConnection.java
src/java/arjdbc/sqlite3/SQLite3RubyJdbcConnection.java

Should fix compile issues on master but I'm not sure whether this method should be restored.

Use precision-accepting BigDecimal.newInstance

---

activerecord-jdbcsqlite3-adapter/activerecord-jdbcsqlite3-adapter.gemspec

Having this upper bound prevents updating jdbc-sqlite3 to any recent version, which in turn prevents Rails 6.1 + JRuby + MacOS + ARM64 from working due to the older sqlite JDBC drivers not having such support.
This commit removes the upper bound so that any newer 3.x jdbc-sqlite3 can be used with Rails 6.1 + JRuby.

Drop upper bound on jdbc-sqlite3

---

Gemfile
bench/benchmark_create.rb
bench/benchmark_update.rb

following up on https://github.com/jruby/activerecord-jdbc-adapter/pull/1115 - mostly to make the update benchmark "useful" ...
each `update!` operation will now enforce an actual DB `UPDATE ...`, numbers:
```
--- RUBY_VERSION: 2.7.5
--- ActiveRecord: 7.0.3
- BenchRecord.connection.drop_table(:bench_records) took 0.01099091
- BenchRecord.connection.create_table(:bench_records) { ... } took 0.002893369
Warming up --------------------------------------
BenchRecord#update() [NOOP]
210.000  i/100ms
BenchRecord#update('a_binary' => "|vR*:\xCA\xA5\xA3\\\x0Ei\xEE\x98\xC4\xE6\xAF...(1536)")
159.000  i/100ms
BenchRecord#update('a_boolean' => true)
87.000  i/100ms
BenchRecord#update('a_date' => Tue, 17 May 2022)
64.000  i/100ms
BenchRecord#update('a_datetime' => Tue, 17 May 2022 09:16:33 +0200) …
```

[chore] adjust update benchmark code

---

lib/arjdbc/mysql/connection_methods.rb

Somewhere between Ruby 2.7 and Ruby 3.1 top-level cvars are not allowed any more.  I changed this to be a constant since I do not see any harm eagerly defining the hash.

Mysql cvar's no longer allowed

---

.gitignore
activerecord-jdbc-adapter.gemspec
lib/arjdbc/abstract/connection_management.rb
lib/arjdbc/abstract/core.rb
lib/arjdbc/abstract/database_statements.rb
lib/arjdbc/abstract/statement_cache.rb
lib/arjdbc/abstract/transaction_support.rb
lib/arjdbc/mysql/adapter.rb
lib/arjdbc/postgresql/adapter.rb
lib/arjdbc/sqlite3/adapter.rb
rakelib/02-test.rake
test/db/mysql/simple_test.rb
test/db/postgresql/version_test.rb
test/db/sqlite3.rb
test/transaction_test_methods.rb

Hi @headius 
Here is some initial work to support active record 7.1.
- More than 90% of ARJDBC tests pass in my local
- The work for sqlite was already there
- The jndi connection pool callbacks is disabled temporarily,we still to work on this
- No sure if we need to update/fix `.github/workflows/ruby.yml`
- I have not run the rails tests yet. I would assume will run.
I can still look at the failing tests and rails tests later the following weeks.

Initial work to support Active Record 7.1 (Rails 7.1.x)

---

jdbc-sqlite3/lib/jdbc/sqlite3/version.rb

JAR from https://github.com/xerial/sqlite-jdbc/releases/tag/3.46.0.0

Update sqlite-jdbc to 3.46

---

jdbc-sqlite3/lib/jdbc/sqlite3/version.rb

Reverts jruby/activerecord-jdbc-adapter#1149
Problem is sqlite3 added a new dependency: **https://github.com/xerial/sqlite-jdbc/commit/21c77a481f6970622b99d712d36d0336d63fd554**

Revert "Update sqlite-jdbc to 3.46"

---

lib/arjdbc/mysql/adapter.rb
test/db/mysql/change_column_test.rb
test/db/mysql/schema_dump_test.rb
test/db/mysql/simple_test.rb

Hi @headius & @enebo 
Here we have more fixes.
Hopefully we will have mysql tests green.

Fix some arjdbc mysql tests to support AR 7.1

---

lib/arjdbc/abstract/connection_management.rb
lib/arjdbc/postgresql/adapter.rb
lib/arjdbc/postgresql/oid_types.rb
lib/arjdbc/postgresql/schema_statements.rb
test/db/postgresql/hstore_test.rb
test/db/postgresql/jdbc_postgres_test.rb
test/db/postgresql/native_types_test.rb
test/db/postgresql/schema_dump_test.rb
test/db/postgresql/simple_test.rb
test/db/postgresql/table_name_test.rb
test/rake_test_support.rb

Hi @headius & @enebo
Hopefully we will have postgres arjdbc tests green.
In the next coming days I will look at Rails tests

Fix some arjdbc postgres tests to support AR 7.1

---

.github/workflows/ruby.yml
lib/arjdbc/postgresql/adapter.rb
test/db/postgresql/table_name_test.rb

Here is fixes to run postgres rails tests
- we need to use postgres 11 since rails tests are incompatible with postgres 10
- I had to skip an arjdbc failing test since is a issue in active record itself. I reproduced the issue in CRuby, https://github.com/rails/rails/issues/52485

Rails booting up and running PostgreSQL rails tests 

---

lib/arjdbc/abstract/database_statements.rb
lib/arjdbc/mysql/adapter.rb
lib/arjdbc/postgresql/adapter.rb
lib/arjdbc/postgresql/oid_types.rb
lib/arjdbc/sqlite3/adapter.rb
src/java/arjdbc/mysql/MySQLRubyJdbcConnection.java

Hi @enebo 
Here are more changes to fix many AR tests.
Also, Rails 7.1 introduced  and new config to handle strict strings for SQLite which the jdbc driver does not support it.
I open a feature request ticket in their repo.
https://github.com/xerial/sqlite-jdbc/issues/1153

Changes to fix many failing tests for MySQL and PostgreSQL

---

lib/arjdbc/abstract/connection_management.rb
lib/arjdbc/postgresql/adapter.rb
lib/arjdbc/postgresql/database_statements.rb
lib/arjdbc/sqlite3/adapter.rb

Hi @enebo 
Here you have more fixes for postgres, the failing tests are under 100
failing tests are in attached file
[postgres_rails_71.txt](https://github.com/user-attachments/files/17987865/postgres_rails_71.txt)

More Postgres fixes to support AR 7.1

---

Gemfile
lib/arjdbc/abstract/relation_query_attribute_monkey_patch.rb
lib/arjdbc/mysql/adapter.rb
lib/arjdbc/postgresql/adapter.rb
lib/arjdbc/postgresql/database_statements.rb
lib/arjdbc/sqlite3/adapter.rb
test/explain_support_test_methods.rb
test/rails/excludes/mysql2/QueryCacheTest.rb
test/rails/excludes/postgresql/QueryCacheTest.rb
test/rails/excludes/sqlite3/QueryCacheTest.rb

Hi @enebo 
The last fix is quite important since common queries would fail for example
```
find_by!(some_field: 1.4)
```
or other queries that use the statement cache.
No sure why the CI does not complete in github workflows, perhaps not enough resources or file descriptor limit, the CI completes fine in my local.
Perhaps we can branch off version 71 and release a RC version and start working in AR 7.2 in master branch.

Some  important fixes

---

lib/arjdbc.rb
src/java/arjdbc/jdbc/RubyJdbcConnection.java
test/simple.rb

Hi @enebo
These fix are kind of important for a common scenarios
1) Use gem from source
```ruby
platforms :jruby do
gem 'activerecord-jdbc-adapter', path: '../../vendor_gems/activerecord-jdbc-adapter'
gem "jdbc-pgsql"
end
```
2) basic query with hardcoded prepared statement
Before Rails 7.2 queries with `where('updated_at < ?', Time.current)` used to be interpolated in AR guts now in Rails 7.2 they pass as part of the prepared statement

Fix using gem from local and basic raw prepared statement with Time.current (active Support time with zone)

---

lib/arjdbc/sqlite3/adapter.rb
src/java/arjdbc/sqlite3/SQLite3RubyJdbcConnection.java

SQLite doesn't store timezone information. In fact, it doesn't even have a real datetime type.
@enebo ,  please double review the Java code. 
AR 8, expect always a Result that respond with a collection.
For the usec hack, i did not understand the test or the hack as Timezone and usec are not supported.

fix: sqlite3 fix , but omitted the time test.

---

activerecord-jdbc-adapter.gemspec

Error:
```sh
There was an error while loading `activerecord-jdbc-adapter.gemspec`: can't modify frozen String,
created at /Users/nicolas/PROJECTS/CONCERTO/concerto/.bundle/jruby/3.4.0/bundler/gems/activerecord-jdbc-adapter-c56c7b476da8/activerecord-jdbc-adapter.gemspec:13.
Bundler cannot continue.
```
Thank you!

Fix bundler error when using --enable=frozen-string-literal

---

test/db/sqlite3/simple_test.rb

We could revisit this after the build is green.

test: removed expectations that SQLite3 understands timezones

---

src/java/arjdbc/sqlite3/SQLite3RubyJdbcConnection.java

This should create less empty result arrays if there are multiple insert/update/deletes.

Create less emptyResults in sqlite3#execute
