jruby/activerecord-jdbc-adapter

lib/arel/visitors/hsqldb.rb, test/db/h2/offset_test.rb, test/db/h2/serialize_test.rb
H2/HSQLDB support standard LIMIT and OFFSET now.
=> Use standard AREL for AR42 with H2/HSQLDB

lib/arjdbc/postgresql/connection_methods.rb
=> Remove comment about pg_params going away

lib/arjdbc/postgresql/adapter.rb
added views to the postgres adapter just like the sqlite adapter, fixes issue #731
=> Add views to postgres adapter

lib/arjdbc/mysql/adapter.rb
This adds views to mysql adapter, just like sqlite and postgres
=> Add views to mysql adapter

lib/arjdbc/postgresql/schema_creation.rb
=> Fix migrations for AR 5.0

test/db/postgresql/oid_types_test.rb
- cast_type was removed from the Column class in ActiveRecord in favor of retrieving types from the model itself
-- https://github.com/rails/rails/commit/155b1b7fe3a1d231fb98a6fb04a21f6eb190b98f
-- https://github.com/rails/rails/commit/158c7eb1d61a28452e0aafd1e05314352eea2749
- accessor was removed from the Column class in ActiveRecord
-- https://github.com/rails/rails/commit/2eb547a4d9cfb4ed1c92397921402048162f5fc8
-- https://github.com/rails/rails/commit/b93b39eff6829ee05ffec1cc8c505f69cbb53fdc#diff-2524057922ad16b58e6b18b2f35b5de2
- the ActiveRecord::ConnectionAdapters::PostgreSQLAdapter::OID::Integer class was removed and now uses ActiveRecord::Type::Integer
=> Fixed OID type tests and removed conditional tests

test/db/postgresql/citext_test.rb, test/db/postgresql/native_types_test.rb, test/db/postgresql/types_test.rb
Also removed some of the conditional checks. The array tests are still not passing since they are a bit more involved to fix
=> Fix most of the tests for postgres adapter types and native types test files

test/db/postgresql/hstore_test.rb
I removed conditional logic and updated the tests to stop using methods that have been removed. I combined the `test_type_cast_hstore` and `test_parse` tests because they have both been testing the same logic since ActiveRecord 4.2 (`type_cast` and `string_to_hstore` both called `type_cast_from_database` on the column).
=> Fixed postgres adapters Hstore tests

Gemfile, lib/arjdbc/jdbc/adapter.rb, lib/arjdbc/postgresql/adapter.rb
ActiveRecord limited the minitest version used and I had to update mocha to the latest because of some issues with JRuby compatibility. Also included a couple of small fixes that cleaned up a few of the tests
=> Fixes for Postgres Adapter against ActiveRecord test suite

src/java/arjdbc/jdbc/RubyJdbcConnection.java, test/db/postgresql/simple_test.rb
The fixes the failing test for multi-statement support and a couple of warnings about ambiguous arguments.
=> Fix multi-statement support

src/java/arjdbc/postgresql/PostgreSQLRubyJdbcConnection.java
Previously bit types were being considered as booleans and would throw an exception when prepared statements were enabled.
Fixes https://github.com/jruby/activerecord-jdbc-adapter/issues/826
=> Fixed bit string support in postgres when using prepared statements

lib/arjdbc/postgresql/adapter.rb
Refer https://github.com/rails/rails/pull/28339
```ruby
$ git clone https://github.com/rails/rails.git
$ bundle install
$ bundle exec rake test:jdbcpostgresql
```
```ruby
$ bundle exec rake test:jdbcpostgresql
... snip ...
Using jdbcpostgresql
NameError: undefined local variable or method `max_identifier_length' for #<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x1f66d8e1>
new_column_from_field at /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb:163
block in columns at /home/yahonda/git/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:167
map at org/jruby/RubyArray.java:2486
columns at /home/yahonda/git/rails/activerecord/lib/active_record/connecti …
```
=> Add `max_identifier_length` and remove its own table_alias_length

lib/arjdbc/mysql/adapter.rb
=> Supply a non-nil column set

lib/arjdbc/sqlite3/adapter.rb
(just a line missing from recent import)
=> [sqlite3] Fix connection.active?

lib/arjdbc/sqlite3/adapter.rb
Two commits with very trivial (almost too trivial to be worth the trouble) fixes for two Rails test failures.
(getting Rails SQLite tests green is so close)
=> [52, sqlite] Trivial Rails test failure fixes

lib/arjdbc/abstract/core.rb
This contains two commits. The first is the actual fix, the second an opinionated performance optimization that people might not like.
=> Fix log bind values

.travis.yml, test/rails/excludes/mysql2/BasicsTest.rb, test/rails/excludes/mysql2/BinaryTest.rb, test/rails/excludes/mysql2/EagerAssociationTest.rb, test/rails/excludes/mysql2/HasManyAssociationsTest.rb, test/rails/excludes/mysql2/UniquenessValidationTest.rb
Encoding of the test DBs was wrong...
Fixes #879
=> [50-52, mysql] Fix CI encoding problems

test/rails/config.yml
Fixes:
* rails/test/cases/adapters/postgresql/prepared_statements_disabled_test.rb
=> [51-52, postgres] Update test/rails/config.yml for missing connection

test/db/postgresql/binary_test.rb
They're passing even with PS...and have for a while via the Rails tests.
=> [51-52, postgres] Execute binary tests again with PS

src/java/arjdbc/postgresql/PostgreSQLRubyJdbcConnection.java, test/rails/excludes/postgresql/PostgresqlEnumTest.rb
=> [50-52, postgres] Support enums with PS

lib/arjdbc/db2/adapter.rb
Merge request from: https://github.com/jruby/activerecord-jdbc-adapter/pull/967
=> [DB2] Refactor DB2 quote method for AR5.1 and up

test/rails/excludes/mysql2/TimePrecisionTest.rb, test/rails/excludes/postgresql/TimePrecisionTest.rb, test/rails/excludes/sqlite3/TimePrecisionTest.rb
Same as with DateTime precision...
=> [test] exclude a time precision test for intermittent failures

.travis.yml, lib/arjdbc/sqlite3/adapter.rb, lib/arjdbc/sqlite3/connection_methods.rb, src/java/arjdbc/jdbc/RubyJdbcConnection.java, src/java/arjdbc/sqlite3/SQLite3RubyJdbcConnection.java, test/db/sqlite3/simple_test.rb, test/rails/excludes/sqlite3/ActiveRecord/DatabaseTasksMigrateStatusTest.rb
This one is all about SQLite3
#980
=> Third batch of Rails 6 changes

Gemfile, lib/arjdbc/postgresql/adapter.rb, src/java/arjdbc/mysql/MySQLRubyJdbcConnection.java, src/java/arjdbc/postgresql/PostgreSQLRubyJdbcConnection.java, test/rails/excludes/mysql2/ActiveRecord/ConnectionAdapters/ConnectionHandlersMultiDbTest.rb, test/rails/excludes/mysql2/Mysql2AdapterTest.rb, test/rails/excludes/postgresql/ActiveRecord/CacheKeyTest.rb, test/rails/excludes/postgresql/ActiveRecord/ConnectionAdapters/ConnectionHandlersMultiDbTest.rb, test/rails/excludes/postgresql/ActiveRecord/ConnectionAdapters/PostgreSQLAdapterTest.rb, test/rails/excludes/sqlite3/ActiveRecord/ConnectionAdapters/ConnectionHandlersMultiDbTest.rb
=> Another batch of Rails 6 changes

.travis.yml, activerecord-jdbc-adapter.gemspec, lib/arjdbc/postgresql/adapter.rb, lib/arjdbc/sqlite3/adapter.rb, test/rails_stub.rb
Fixes current Rails master, doesn't break v6.0.0.beta2
=> Rails 6 fixes

.travis.yml, lib/arjdbc/mysql/adapter.rb, lib/arjdbc/postgresql/adapter.rb, lib/arjdbc/sqlite3/adapter.rb, test/db/mysql/connection_test.rb, test/db/postgresql/simple_test.rb, test/db/postgresql/version_test.rb, test/db/sqlite3/simple_test.rb, test/rails/excludes/mysql2/FixturesTest.rb, test/rails/excludes/postgresql/ActiveRecord/ConnectionAdapters/PostgreSQLAdapterTest.rb
This contains updates to run against current Rails master. The CI job is changed for that. Also java 11 tests are enabled again
=> Rails 6-master fixes

.travis.yml
Fixes build failures due to AR moving on and those changes not being handled yet
=> Build against AR 6-0-stable instead of master

src/java/arjdbc/util/DateTimeUtils.java
Extracted from #1008, credit goes to @rdubya
=> [core] fix nanoseconds handling for Timestamps

rakelib/01-tomcat.rake
=> [rake] fix download from maven repo

.travis.yml, lib/arel/visitors/postgresql_jdbc.rb, lib/arjdbc/abstract/database_statements.rb, lib/arjdbc/abstract/transaction_support.rb, lib/arjdbc/postgresql/adapter.rb, lib/arjdbc/postgresql/oid_types.rb, lib/arjdbc/sqlite3/adapter.rb, src/java/arjdbc/jdbc/RubyJdbcConnection.java, src/java/arjdbc/postgresql/PostgreSQLRubyJdbcConnection.java, test/db/postgresql/types_test.rb, test/db/postgresql/unit_test.rb, test/rails/excludes/mysql2/ActiveRecord/Migration/NoForeignKeySupportTest.rb, test/rails/excludes/mysql2/ActiveRecord/TooManyOrTest.rb, test/rails/excludes/postgresql/ActiveRecord/Migration/IndexTest.rb, test/rails/excludes/postgresql/ActiveRecord/TooManyOrTest.rb, test/rails/excludes/postgresql/CalculationsTest.rb, test/rails/excludes/postgresql/MigrationTest.rb
=> Rails 6.1 fixes

src/java/arjdbc/jdbc/RubyJdbcConnection.java
Hi! This PR is a fix for [this](https://github.com/jruby/activerecord-jdbc-adapter/issues/1065) issue
=> Fix date time zone for date columns

activerecord-jdbcmysql-adapter/activerecord-jdbcmysql-adapter.gemspec
=> fix(mysql): fix dependency for jdbc-mysql

.github/workflows/ruby.yml
Moving off Travis to GHA... gonna take some work.
=> Move CI testing to GHA

lib/arjdbc/abstract/core.rb
align with upstream Rails 7.0 and a few nice to haves
=> [refactor] minor core updates

.github/workflows/ruby.yml, activerecord-jdbcsqlite3-adapter/activerecord-jdbcsqlite3-adapter.gemspec, jdbc-sqlite3/lib/jdbc/sqlite3/version.rb
For M1 support, as per https://stackoverflow.com/questions/70048681/java-sql-sqlexception-error-opening-connection.
Not sure what this upgrade involves, but this does get things going on my machine.
Fixes #1118.
=> Bump sqlite-jdbc adapter

jdbc-sqlite3/lib/jdbc/sqlite3/version.rb
=> Update sqlite3 jdbc to 3.46.1.1

Rakefile, pom.xml, rakelib/rails.rake
@enebo , switched to java 11 target .
Now we have lot of test to fix. I'm on it.
=> remove invalid monkey patch require
